#!/bin/bash
# It is required to have "zenity" package installed to use this script
# In debian based distros you can install it using this command:
# apt install zenity

FONT_CONFIG='FontName=Segoe UI Bold,Fontsize=24,PrimaryColour=&H00FFFF&'

cut_vid() {
    file="$(zenity --file-selection 2> /dev/null)"
    dirname="$(dirname "$file")"
    [ -n $1 ] && sub="$(zenity --title="Subtitle" --file-selection 2> /dev/null)"
    output="$(zenity --title="Output file" --text "Name?" --entry 2> /dev/null)"

    echo -n "Inicio? 0123 " ; read inicio
    echo -n "Fim?  0259 " ; read fim

    if [[ -n $file  && -n $output  && -n $inicio && -n $fim ]]
    then  
        if [[ $(echo -n $inicio | wc -c) -eq  6 ]]
        then
            if [ -n $1 ]
            then
                ffmpeg -i "$file" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" -vf "subtitles='$sub':force_style='$FONT_CONFIG" "$dirname"/"${output// /_}".mp4
                echo -e "\nffmpeg -i \""$file"\" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" -vf \"subtitles='$sub':force_style='$FONT_CONFIG\" \"$dirname/"${output// /_}".mp4\"" | tee | xclip -i -selection clipboard
            else
                ffmpeg -i "$file" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" "$dirname"/"${output// /_}".mp4
                echo -e "\nffmpeg -i \""$file"\" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" \"$dirname/"${output// /_}".mp4\"" | tee | xclip -i -selection clipboard
            fi

        elif [[ $(echo -n $inicio | wc -c) -eq  4 ]]
        then
            if [ -n $1 ]
            then
                ffmpeg -i "$file" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" -vf "subtitles='$sub':force_style='$FONT_CONFIG" "$dirname"/"${output// /_}".mp4
                echo -e "\nffmpeg -i \""$file"\" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" -vf \"subtitles='$sub':force_style='$FONT_CONFIG\" \"$dirname/"${output// /_}".mp4\"" | tee | xclip -i -selection clipboard
            else    
                ffmpeg -i "$file" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" "$dirname"/"${output// /_}".mp4
                echo -e "\nffmpeg -i \""$file"\" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" \"$dirname/\"${output// /_}\".mp4\"" | tee | xclip -i -selection clipboard
            fi
        else
            echo "O registro do tempo precisa ter 4 ou 6 digitos, obrigatoriamente! 1:03 precisa ser 0103"
        fi
    else
        echo "Alguma das variáveis é nula"
    fi
}

subtitle() {
    input="$(zenity --title="Input file" --file-selection 2> /dev/null)"
    dirname="$(dirname "$input")"
    sub="$(zenity --title="Subtitle" --file-selection 2> /dev/null)"
    output="$(zenity --title="Output file" --text "Name?" --entry 2> /dev/null)"
    
    ffmpeg -i "$input" -vf "subtitles='$sub':force_style='$FONT_CONFIG" -acodec copy -max_muxing_queue_size 1024 "$dirname"/"${output}".mp4
    echo -e "ffmpeg -i ${input} -vf \"subtitles=${sub}:force_style='$FONT_CONFIG'\" -acodec copy -max_muxing_queue_size 1024 $dirname/${output}.mp4" | tee | xclip -i -selection clipboard
}

echo -e "\
        1_CORTAR\n\
        2_CORTAR COM LEGENDAS\n\
        3_LEGENDAS\n :"

while [[ ($resp != 1) && ($resp != 2) && ($resp != 3) ]]
do
    read -p "# " resp
    case $resp in
        1) echo "Cortar vídeo..."
        cut_vid
        ;; 
        2) echo "Cortar vídeo com legenda..."
        cut_vid sub
        ;;
        3) echo "Gravar legenda..."
        subtitle
        ;;
        *) echo "Opção inválida"
    esac
done

exit 0
