#!/bin/bash
# ed_video by Leonardo Bernardes
# The script required the "zenity" package installed to be used
# In debian based distros you can install it using this command:
# apt install zenity

FONT_CONFIG='FontName=Segoe UI Bold,Fontsize=25,PrimaryColour=&H00FFFF&'

[[ $LANGUAGE == "pt_BR" ]] && { 
    LAST="1) CORTAR\n2) CORTAR_COM_LEGENDAS\n3) LEGENDAS\n4) CORTAR LEGENDA\n5) SAIR"
    INICIO="Início"
    FIM="Fim"
    LEGENDA="Legenda convertida pro código de caratéres UTF-8"
    UM="O registro do tempo precisa ter 4 ou 6 digitos, obrigatoriamente! 1:03 precisa ser 0103"
    DOIS="Alguma das variáveis é nula"
    TRES="Cortar vídeo..."
    QUATRO="Cortar vídeo com legenda..."
    CINCO="Gravar legenda..."
    SEIS="Opção inválida"
    SETE="Cortar legendas..."
    TERM="Terminado!"
    OITO="S"
}

[[ $LANGUAGE == "en_US" ]] || [[ -z $LANGUAGE ]] || [[ $LANGUAGE != "pt_BR" ]] && {
    LAST="1) TO CUT\n2) TO CUT WITH SUBTITLES\n3) TO HARDCODE SUBTITLES\n4) TO CUT SUBTITLES\n5) EXIT"
    INICIO="Beginning"
    FIM="End"
    LEGENDA="Subtitle converted to UTF-8 charset"
    UM="Time register must necessarily have 4 or 6 digits! 1:03 must be 0103"
    DOIS="Some variable is null"
    TRES="To cut video..."
    QUATRO="To cut with subtitles..."
    CINCO="To hardcode subtitles..."
    SEIS="Invalid option"
    SETE="To cut subtitles..."
    TERM="Finished!"
}

cut_vid() {
    file="$(zenity --title="File" --file-selection 2> /dev/null)"
    filename="$(basename -- "$file")"
    extension="${filename##*.}"
    dirname="$(dirname "$file")"
    [[ $extension == "mkv" ]] && scodec="srt" || scodec="mov_text"

    [[ -n $1 ]] && {
        sub="$(zenity --title="Subtitle" --file-selection --filename="$file" 2> /dev/null)"
        # check if subtitle file is coded in utf-8 charset. Otherwise we will get an error while encoding the video
        charset="$(file -i "$sub" |tr ' ' '\n' |grep -i charset |cut -d= -f2)"
        if [  "$charset" != "utf-8" ]
        then
            new_name="$dirname"/$(mktemp -u legenda_XXXXXX).srt
            iconv -f "$charset" -t utf-8 "$sub" -o "$new_name"
            sub="$new_name"
            echo "$LEGENDA"
            # to strip any formatting settings
            [[ -n $(cat "$sub" |grep -i font ) ]] && sed -i -e 's/<[^>]*>//g' -e 's/^ //' "$sub"
        fi
    }
    output="$(zenity --title="Output file" --text "Name?" --entry 2> /dev/null)"

    echo -n "$INICIO? 0123 " ; read inicio
    echo -n "$FIM?  0259 " ; read fim
    echo -e "$inicio $fim\n$output\n" >> "$dirname"/INFO

    if [[ -n $file  && -n $output  && -n $inicio && -n $fim ]]
    then  
        if [[ $(echo -n $inicio | wc -c) -eq  6 ]]
        then
            if [[ -n $1 ]]
            then
                cmd="ffmpeg -i \"$file\" -i \"$sub\" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" -scodec $scodec -acodec copy -vcodec h264 -qp 12 \"$dirname\"/"${output// /_}"."$extension""
                eval $cmd
                echo $cmd | xclip -i -selection clipboard
                ffmpeg -i "$sub" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" "$dirname"/"${output// /_}".srt
                # rm "$sub"
                # ffmpeg -i "$dirname"/"${output// /_}"."$extension" -map 0:s:0 "$dirname"/"${output// /_}".srt
            else
                cmd="ffmpeg -i \"$file\" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" -acodec copy -vcodec h264 -qp 12  \"$dirname\"/"${output// /_}"."$extension""
                eval $cmd
                echo $cmd | xclip -i -selection clipboard
            fi

        elif [[ $(echo -n $inicio | wc -c) -eq  4 ]]
        then
            if [[ -n $1 ]]
            then
                cmd="ffmpeg -i \"$file\" -i \"$sub\" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" -scodec $scodec -acodec copy -vcodec h264 -qp 12 \"$dirname\"/"${output// /_}"."$extension""
                eval $cmd
                echo $cmd | xclip -i -selection clipboard
                ffmpeg -i "$sub" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" "$dirname"/"${output// /_}".srt
                # rm "$sub"
                # ffmpeg -i "$dirname"/"${output// /_}"."$extension" -map 0:s:0 "$dirname"/"${output// /_}".srt
            else    
                cmd="ffmpeg -i \"$file\" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" -acodec copy -vcodec h264 -qp 12 \"$dirname\"/"${output// /_}"."$extension""
                eval $cmd
                echo $cmd | xclip -i -selection clipboard
            fi
        else
            echo "$UM"
        fi
    else
        echo "$DOIS"
    fi
    notify-send -u critical -t 600 -i task-due "ED_VIDEO" "$TERM"

}

cut_subtitles() {
    sub="$(zenity --title="Input file" --file-selection 2> /dev/null)"
    dirname="$(dirname "$sub")"
    output="$(zenity --title="Output file" --text "Name?" --entry 2> /dev/null).srt"
    charset="$(file -i "$sub" |tr ' ' '\n' |grep -i charset |cut -d= -f2)"
    if [  "$charset" != "utf-8" ]
    then
        new_name="$dirname"/$(mktemp -u legenda_XXXXXX).srt
        iconv -f "$charset" -t utf-8 "$sub" -o "$new_name"
        sub="$new_name"
        echo "$sub"
        echo "$LEGENDA"
        [[ -n $(cat "$sub" |grep -i font ) ]] && sed -i -e 's/<[^>]*>//g' -e 's/^ //' "$sub"
    fi

    echo -n "$INICIO? 0123 " ; read inicio
    echo -n "$FIM?  0259 " ; read fim
    echo -e "$inicio $fim\n$output\n" >> "$dirname"/INFO

    if [[ -n $sub  && -n $output  && -n $inicio && -n $fim ]]
    then  
        if [[ $(echo -n $inicio | wc -c) -eq  6 ]]
        then
            cmd="ffmpeg -i \"$sub\" -ss "${inicio:0:2}":"${inicio:2:2}":"${inicio:4:2}" -to "${fim:0:2}":"${fim:2:2}":"${fim:4:2}" -scodec copy \"$dirname\"/"${output// /_}""
            eval $cmd
            echo $cmd | xclip -i -selection clipboard
        elif [[ $(echo -n $inicio | wc -c) -eq  4 ]]
        then
            cmd="ffmpeg -i \"$sub\" -ss "${inicio:0:2}":"${inicio:2:2}" -to "${fim:0:2}":"${fim:2:2}" -scodec copy \"$dirname\"/"${output// /_}""
            eval $cmd
            echo $cmd | xclip -i -selection clipboard
        else
            echo "$UM"
        fi
    else
        echo "$DOIS"
    fi
    [[ -e "$new_name" ]] && rm "$new_name"
    notify-send -u critical -t 600 -i task-due "ED_VIDEO" "$TERM"
}

subtitle_hardcoded() {
    file="$(zenity --title="Input file" --file-selection 2> /dev/null)"
    dirname="$(dirname "$file")"
    filename="$(basename -- "$file")"
    name="${filename%.*}"
    [[ -e $dirname/$name.srt ]] && sub="$dirname/$name.srt" || sub="$(zenity --title="Subtitle" --file-selection --filename="$dirname" 2> /dev/null)"
    output="$(zenity --title="Output file" --text "Name?" --entry 2> /dev/null)"
    [[ -n $(cat $sub |grep -i font ) ]] && sed -i -e 's/<[^>]*>//g' -e 's/^ //' "$sub"
    
    cmd="ffmpeg -i \"$file\" -vf \"subtitles='${sub}':force_style='${FONT_CONFIG}'\" -crf 14 -max_muxing_queue_size 1024 \"$dirname\"/"${output// /_}".mp4"
    eval $cmd
    echo $cmd | xclip -i -selection clipboard
    notify-send -u critical -t 600 -i task-due "ED_VIDEO" "$TERM"
}

echo -e "$LAST"

while [[ ($resp != 1) && ($resp != 2) && ($resp != 3) && ($resp != 4) && ($resp != 5) ]]
do
    read -p "#) " resp
    case $resp in
        1) echo "$TRES"
        cut_vid
        ;; 
        2) echo "$QUATRO"
        cut_vid sub
        ;;
        3) echo "$CINCO"
        subtitle_hardcoded
        ;;
        4) echo "$SETE"
        cut_subtitles
        ;;
        5) echo "$OITO"
        exit 0
        ;;
        *) echo "$SEIS"
    esac
done